### ISSUE TITLE
OpenSpin accepts constants that exceed 32 bits

### ISSUE THREAD

**Issue by dcarrier-parallax** [parallaxinc/OpenSpin#31] opened 2016-10-07 01:06 UTC
The following program compiles successfully with OpenSpin:

> pub main | x
> x := $FF_FF_FF_FF_FF

The program should not compile, because it attempts to store a 40-bit constant into 'x'.
An attempt to compile with the Propeller tool returns this error:

> Constant exceeds 32 bits.

OpenSpin should generate a similar error.

**Comment by avsa242** [comment] 2016-12-05 13:26
@dcarrier-parallax,

I don't see a newer commit since your post on Oct 6, but this seems to work in fe4797b13e1d586b04923c513c44e8af410b0a92, can you confirm?

**Comment by reltham** [comment] 2018-02-26 02:37
This is a duplicate of issue #23 which was fixed already. Closing.

**Closed by reltham** 2018-02-26 02:37 UTC
Labels: bug, duplicate
